apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "admission-webhook.fullname" . }}
spec:
  commonName: {{ include "admission-webhook.fullname" . }}.{{ .Release.Namespace }}.svc
  dnsNames:
    - {{ include "admission-webhook.fullname" . }}
    - {{ include "admission-webhook.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "admission-webhook.fullname" . }}.{{ .Release.Namespace }}.svc
  isCA: true
  privateKey:
    algorithm: RSA
    size: 2048
  duration: 48h
  renewBefore: 24h
  secretName: {{ include "admission-webhook.fullname" . }}-certificate
  issuerRef:
    name: {{ include "admission-webhook.fullname" . }}
    kind: Issuer
  usages:
    - server auth
    - client auth
    - key encipherment
    - digital signature
